import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const paperTrades = sqliteTable(
  "paper_trades",
  {
    id: text("id").primaryKey(),
    signalKey: text("signal_key").notNull(),
    symbol: text("symbol").notNull(),
    baseAsset: text("base_asset").notNull(),
    direction: text("direction", { enum: ["LONG", "SHORT"] }).notNull(),
    setupType: text("setup_type").notNull(),
    modelVersion: text("model_version").notNull().default("V1"),
    status: text("status", { enum: ["OPEN", "TP", "SL", "MANUAL"] }).notNull().default("OPEN"),
    rankingScore: integer("ranking_score").notNull(),
    technicalScore: integer("technical_score").notNull(),
    entryPrice: real("entry_price").notNull(),
    stopLoss: real("stop_loss").notNull(),
    takeProfit: real("take_profit").notNull(),
    takeProfit2: real("take_profit_2").notNull(),
    takeProfit3: real("take_profit_3").notNull(),
    marginUsd: real("margin_usd").notNull().default(10),
    leverage: real("leverage").notNull().default(20),
    roundTripCostRate: real("round_trip_cost_rate").notNull().default(0.001),
    exitPrice: real("exit_price"),
    outcomeR: real("outcome_r"),
    openedAt: text("opened_at").notNull(),
    closedAt: text("closed_at"),
    lastCheckedAt: text("last_checked_at").notNull(),
    observedHigh: real("observed_high").notNull(),
    observedLow: real("observed_low").notNull(),
    sourceClosedAt: integer("source_closed_at").notNull(),
    evidenceJson: text("evidence_json").notNull(),
  },
  (table) => [
    uniqueIndex("paper_trades_signal_key_unique").on(table.signalKey),
    index("paper_trades_status_opened_idx").on(table.status, table.openedAt),
    index("paper_trades_symbol_opened_idx").on(table.symbol, table.openedAt),
  ],
);

export const shadowObservations = sqliteTable(
  "shadow_observations",
  {
    id: text("id").primaryKey(),
    signalKey: text("signal_key").notNull(),
    symbol: text("symbol").notNull(),
    baseAsset: text("base_asset").notNull(),
    direction: text("direction", { enum: ["LONG", "SHORT"] }).notNull(),
    regime: text("regime").notNull(),
    earlyStatus: text("early_status"),
    eligible: integer("eligible", { mode: "boolean" }).notNull(),
    technicalScore: integer("technical_score").notNull(),
    longScore: integer("long_score").notNull(),
    shortScore: integer("short_score").notNull(),
    scoreDelta: integer("score_delta").notNull(),
    entryPrice: real("entry_price").notNull(),
    stopLoss: real("stop_loss").notNull(),
    takeProfit: real("take_profit").notNull(),
    status: text("status", { enum: ["OPEN", "TP", "SL", "EXPIRED"] }).notNull().default("OPEN"),
    outcomeR: real("outcome_r"),
    openedAt: text("opened_at").notNull(),
    closedAt: text("closed_at"),
    lastCheckedAt: text("last_checked_at").notNull(),
    observedHigh: real("observed_high").notNull(),
    observedLow: real("observed_low").notNull(),
    sourceClosedAt: integer("source_closed_at").notNull(),
    crossExchangeStatus: text("cross_exchange_status"),
    crossExchangeHash: text("cross_exchange_hash"),
    evaluationVersion: text("evaluation_version").notNull().default("V1_SAMPLED_MARK"),
    outcomeSource: text("outcome_source").notNull().default("SAMPLED_MARK"),
    evidenceHash: text("evidence_hash").notNull(),
  },
  (table) => [
    uniqueIndex("shadow_observations_signal_key_unique").on(table.signalKey),
    index("shadow_observations_status_opened_idx").on(table.status, table.openedAt),
    index("shadow_observations_symbol_opened_idx").on(table.symbol, table.openedAt),
    index("shadow_observations_direction_regime_idx").on(table.direction, table.regime),
  ],
);

export const paperRuntimeState = sqliteTable("paper_runtime_state", {
  id: text("id").primaryKey(),
  dataHealthState: text("data_health_state", { enum: ["HEALTHY", "DEGRADED", "UNKNOWN"] }).notNull(),
  entryCircuit: text("entry_circuit", { enum: ["OPEN", "BLOCKED"] }).notNull(),
  reasonsJson: text("reasons_json").notNull(),
  cooldownBlockedJson: text("cooldown_blocked_json").notNull(),
  lastSyncAt: text("last_sync_at").notNull(),
});

export const telegramSubscriptions = sqliteTable("telegram_subscriptions", {
  chatId: text("chat_id").primaryKey(),
  userId: text("user_id").notNull(),
  username: text("username"),
  state: text("state", { enum: ["ACTIVE", "BLOCKED"] }).notNull().default("ACTIVE"),
  pairedAt: text("paired_at").notNull(),
  lastSeenAt: text("last_seen_at").notNull(),
});

export const telegramSettings = sqliteTable("telegram_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const telegramTradeMonitors = sqliteTable(
  "telegram_trade_monitors",
  {
    id: text("id").primaryKey(),
    signalKey: text("signal_key").notNull(),
    chatId: text("chat_id"),
    messageId: text("message_id"),
    symbol: text("symbol").notNull(),
    baseAsset: text("base_asset").notNull(),
    direction: text("direction", { enum: ["LONG", "SHORT"] }).notNull(),
    setupType: text("setup_type").notNull(),
    decision: text("decision", { enum: ["OFFERED", "EXECUTED", "PASSED", "EXPIRED", "CLOSED"] }).notNull().default("OFFERED"),
    monitorState: text("monitor_state").notNull().default("OFFERED"),
    rankingScore: integer("ranking_score").notNull(),
    plannedEntry: real("planned_entry").notNull(),
    actualEntry: real("actual_entry"),
    stopLoss: real("stop_loss").notNull(),
    tp1: real("tp1").notNull(),
    tp2: real("tp2").notNull(),
    tp3: real("tp3").notNull(),
    sourceClosedAt: integer("source_closed_at").notNull(),
    offeredAt: text("offered_at").notNull(),
    decidedAt: text("decided_at"),
    lastCheckedAt: text("last_checked_at"),
    lastAlertHash: text("last_alert_hash"),
    evidenceJson: text("evidence_json").notNull(),
  },
  (table) => [
    uniqueIndex("telegram_monitors_signal_key_unique").on(table.signalKey),
    index("telegram_monitors_decision_state_idx").on(table.decision, table.monitorState),
    index("telegram_monitors_symbol_offered_idx").on(table.symbol, table.offeredAt),
  ],
);

export const telegramEvents = sqliteTable(
  "telegram_events",
  {
    id: text("id").primaryKey(),
    monitorId: text("monitor_id").notNull(),
    event: text("event").notNull(),
    occurredAt: text("occurred_at").notNull(),
    evidenceHash: text("evidence_hash").notNull(),
    payloadJson: text("payload_json").notNull(),
    deliveryStatus: text("delivery_status", { enum: ["PENDING", "SENT", "FAILED", "NOT_REQUIRED"] }).notNull(),
  },
  (table) => [index("telegram_events_monitor_time_idx").on(table.monitorId, table.occurredAt)],
);

export const viewerLoginAttempts = sqliteTable("viewer_login_attempts", {
  identifierHash: text("identifier_hash").primaryKey(),
  failedCount: integer("failed_count").notNull().default(0),
  windowStartedAt: text("window_started_at").notNull(),
  blockedUntil: text("blocked_until"),
  updatedAt: text("updated_at").notNull(),
});

export const exitShadowPositions = sqliteTable(
  "exit_shadow_positions",
  {
    id: text("id").primaryKey(),
    paperTradeId: text("paper_trade_id").notNull(),
    symbol: text("symbol").notNull(),
    baseAsset: text("base_asset").notNull(),
    direction: text("direction", { enum: ["LONG", "SHORT"] }).notNull(),
    sourceModelVersion: text("source_model_version").notNull(),
    sourceStatus: text("source_status", { enum: ["OPEN", "TP", "SL"] }).notNull(),
    state: text("state").notNull().default("OPEN"),
    entryPrice: real("entry_price").notNull(),
    originalStop: real("original_stop").notNull(),
    activeStop: real("active_stop").notNull(),
    oneRPrice: real("one_r_price").notNull(),
    tp1: real("tp1").notNull(),
    tp2: real("tp2").notNull(),
    tp3: real("tp3").notNull(),
    remainingFraction: real("remaining_fraction").notNull().default(1),
    realizedR: real("realized_r").notNull().default(0),
    baselineOutcomeR: real("baseline_outcome_r"),
    openedAt: text("opened_at").notNull(),
    lastCheckedAt: text("last_checked_at").notNull(),
    closedAt: text("closed_at"),
    evidenceJson: text("evidence_json").notNull(),
  },
  (table) => [
    uniqueIndex("exit_shadow_paper_trade_unique").on(table.paperTradeId),
    index("exit_shadow_state_checked_idx").on(table.state, table.lastCheckedAt),
    index("exit_shadow_symbol_opened_idx").on(table.symbol, table.openedAt),
  ],
);

export const backgroundScanRuns = sqliteTable(
  "background_scan_runs",
  {
    id: text("id").primaryKey(),
    cycleKey: text("cycle_key").notNull(),
    version: text("version").notNull(),
    mode: text("mode", { enum: ["PAPER_SHADOW_READ_ONLY"] }).notNull(),
    state: text("state", { enum: ["RUNNING", "COMPLETED", "PARTIAL", "FAILED"] }).notNull(),
    startedAt: text("started_at").notNull(),
    completedAt: text("completed_at"),
    evidenceHash: text("evidence_hash").notNull(),
    summaryJson: text("summary_json").notNull(),
  },
  (table) => [
    uniqueIndex("background_scan_runs_cycle_key_unique").on(table.cycleKey),
    index("background_scan_runs_state_started_idx").on(table.state, table.startedAt),
  ],
);

export const hotVolumeObservations = sqliteTable(
  "hot_volume_observations",
  {
    id: text("id").primaryKey(),
    signalKey: text("signal_key").notNull(),
    cohortKey: text("cohort_key").notNull(),
    evaluationVersion: text("evaluation_version").notNull(),
    variant: text("variant", { enum: ["RAW", "HARDENED"] }).notNull(),
    symbol: text("symbol").notNull(),
    baseAsset: text("base_asset").notNull(),
    direction: text("direction", { enum: ["LONG", "SHORT"] }).notNull(),
    radarStatus: text("radar_status").notNull(),
    radarScore: integer("radar_score").notNull(),
    entryPrice: real("entry_price").notNull(),
    stopLoss: real("stop_loss").notNull(),
    takeProfit: real("take_profit").notNull(),
    atr15m: real("atr_15m").notNull(),
    status: text("status", { enum: ["OPEN", "TP", "SL", "EXPIRED"] }).notNull().default("OPEN"),
    outcomeR: real("outcome_r"),
    exitPrice: real("exit_price"),
    openedAt: text("opened_at").notNull(),
    closedAt: text("closed_at"),
    lastCheckedAt: text("last_checked_at").notNull(),
    observedHigh: real("observed_high").notNull(),
    observedLow: real("observed_low").notNull(),
    sourceClosedAt: text("source_closed_at").notNull(),
    openEvidenceHash: text("open_evidence_hash").notNull(),
    outcomeEvidenceHash: text("outcome_evidence_hash"),
    evidenceJson: text("evidence_json").notNull(),
  },
  (table) => [
    uniqueIndex("hot_volume_observations_signal_key_unique").on(table.signalKey),
    index("hot_volume_observations_status_opened_idx").on(table.status, table.openedAt),
    index("hot_volume_observations_cohort_variant_idx").on(table.cohortKey, table.variant),
    index("hot_volume_observations_symbol_opened_idx").on(table.symbol, table.openedAt),
  ],
);

export const haxkaiShadowObservations = sqliteTable(
  "haxkai_shadow_observations",
  {
    id: text("id").primaryKey(),
    signalKey: text("signal_key").notNull(),
    symbol: text("symbol").notNull(),
    baseAsset: text("base_asset").notNull(),
    direction: text("direction", { enum: ["LONG", "SHORT"] }).notNull(),
    levelPrice: real("level_price").notNull(),
    levelLabel: text("level_label").notNull(),
    volumeRatio: real("volume_ratio").notNull(),
    entryPrice: real("entry_price").notNull(),
    stopLoss: real("stop_loss").notNull(),
    takeProfit: real("take_profit").notNull(),
    targetR: real("target_r").notNull(),
    status: text("status", { enum: ["OPEN", "TP", "SL", "EXPIRED"] }).notNull().default("OPEN"),
    outcomeR: real("outcome_r"),
    exitPrice: real("exit_price"),
    openedAt: text("opened_at").notNull(),
    closedAt: text("closed_at"),
    lastCheckedAt: text("last_checked_at").notNull(),
    observedHigh: real("observed_high").notNull(),
    observedLow: real("observed_low").notNull(),
    sourceClosedAt: integer("source_closed_at").notNull(),
    evidenceHash: text("evidence_hash").notNull(),
    evidenceJson: text("evidence_json").notNull(),
  },
  (table) => [
    uniqueIndex("haxkai_shadow_signal_key_unique").on(table.signalKey),
    index("haxkai_shadow_status_opened_idx").on(table.status, table.openedAt),
    index("haxkai_shadow_symbol_opened_idx").on(table.symbol, table.openedAt),
    index("haxkai_shadow_direction_opened_idx").on(table.direction, table.openedAt),
  ],
);
